/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_work_demoset_jni_JNIUtil */

#ifndef _Included_com_android_work_demoset_jni_JNIUtil
#define _Included_com_android_work_demoset_jni_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_work_demoset_jni_JNIUtil
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_android_work_demoset_jni_JNIUtil_nativeInit
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_android_work_demoset_jni_JNIUtil
 * Method:    nativeTest
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_work_demoset_jni_JNIUtil_nativeTest
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
